CREATE TABLE Timesheets (
    Id INT PRIMARY KEY IDENTITY(1,1),
    OrchardId UNIQUEIDENTIFIER NOT NULL,
    SupervisorId UNIQUEIDENTIFIER NOT NULL,
    PickerId UNIQUEIDENTIFIER NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    Activity NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_Timesheet_Orchard FOREIGN KEY (OrchardId) REFERENCES Orchards(Id)
);
